version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "./data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  dynamodb:
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
#  fastapi:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: fastapi
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/code/app
#      - ./requirements.txt:/code/requirements.txt
#    depends_on:
#      - minio
#      - dynamodb-local
#    environment:
#      - OPENAI_API_KEY=${OPENAI_API_KEY}   # if you use OpenAI
#    restart: unless-stopped
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API endpoint
      - "9001:9001"   # MinIO Console (web UI)
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY: "http://host.docker.internal:8080/document/process"
    volumes:
      - ./minio_data:/data
      - ./entrypoint.sh:/entrypoint.sh
    command: server /data --console-address ":9001"
    restart: unless-stopped
